---
title: "Bed-2056 Exam"
author: "Asbjorn Aarekol & Morten Ostrem"
date: "12/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	include = FALSE
)
```

```{r create data, include=FALSE}
rm(list=ls())

# load packages
library(tidyverse)
library(rvest)
library(readxl)

# Read the happines data from the UN from the CSV and put it in a dataframe
# Using the data from 2017 as the wikipedia data is also from 2017
# Data gotten from kaggle
df2017 <- read_csv('2017.csv')

# Create a dataframe for all homicide worldwide and remove the source collums
# Remove the subregion rows aswell
# Data gotten from dataUNODC
homicide_df <- read_excel('homicide_all.xls') %>% 
  subset(., select = c(1:7)) %>% 
  filter(., Indicator == 'Firearms rate')

# Find the table from wikipedia and return a dataframe
table <- "https://en.wikipedia.org/wiki/Estimated_number_of_civilian_guns_per_capita_by_country" %>%
  read_html() %>%
  html_nodes(xpath='//table[1]') %>% 
  html_table(fill = TRUE) %>% 
  data.frame()


# Rename the variables in the wikipedia table df and merge it with the happines data
table <- table %>% 
  rename("Country" = Country..or.dependent.territory..subnational.area..etc..) %>% 
  rename("Firearms100" = Estimate.of.civilian.firearms.per.100.persons) %>% 
  rename("Firearms_estimate" = Estimate.of.firearms.in.civilian.possession) %>% 
  rename("Reg_firearm" = Registered.firearms) %>% 
  rename("Unreg_firearm" = Unregistered.firearms) %>% 
  rename("Population" = Population.2017) %>% 
  mutate(Population = sub(",", "", Population, fixed = FALSE)) %>% 
  mutate(Population = sub(",", "", Population, fixed = FALSE)) %>%
  mutate(Population = sub(",", "", Population, fixed = FALSE)) %>% 
  mutate(Population = as.numeric(Population)) %>% 
  select(Country, Firearms100, Firearms_estimate, Reg_firearm, Unreg_firearm, Population, Region) %>% 
  merge(., df2017)

```

## Plot of firearms per 100 inhabitant

```{r 100fire , echo=FALSE}

# Plot the countries sorted in a barplot
ggplot(table, aes(reorder(Country, Firearms100), Firearms100, fill = Region)) +
  geom_bar(stat = "identity", show.legend = TRUE) +
  theme(strip.text.y = element_text(angle = 0),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 6),
        axis.title.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank())
```

```{r fire100 vs happines, echo=FALSE}

# Plot the firearms100 vs happines
ggplot(table, aes(Happiness.Score, Firearms100, color = Country, size = Population)) +
  geom_jitter(aes(), show.legend = FALSE) +
  geom_text(aes(label=ifelse(Firearms100>25,as.character(Country),'')), hjust=1,vjust=0, show.legend = FALSE) +
  geom_text(aes(label=ifelse(Population>120000000,as.character(Country),'')), hjust=1,vjust=0, show.legend = FALSE)


```

```{r fire100 vs GDP, echo=FALSE}

# Plot the firearms100 vs happines
ggplot(table, aes(Economy..GDP.per.Capita., Firearms100, color = Country, size = Population)) +
  geom_jitter(aes(), show.legend = FALSE)


```


```{r fire100 vs Life expectany, echo=FALSE}

# Plot the firearms100 vs happines
ggplot(table, aes(Health..Life.Expectancy., Firearms100, color = Country, size = Population)) +
  geom_jitter(aes(), show.legend = FALSE)


```

```{r homicide over the years by subregion, echo=FALSE}
ggplot(homicide_df, aes(Year, Value, group = Subregion, fill = Subregion)) +
  geom_bar(stat = 'identity', show.legend = FALSE) +
  facet_wrap(~Subregion) +
  theme_light() +
  theme(axis.text.y.left = element_blank())

```


